// Ingredients
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENT = 'SET_INGREDIENT';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';
export const FETCH_INGREDIENTS = 'FETCH_INGREDIENTS';

// Burger
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_INIT = "PURCHASE_INIT";
export const PURCHASE_BURGER_START_SAGA = 'PURCHASE_BURGER_START_SAGA';
// Order
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAIL = 'FETCH_ORDER_FAIL';
export const FETCH_ORDER_INIT = 'FETCH_ORDER_INIT';
export const FETCH_USER_SPECIFIC_ORDER = 'FETCH_USER_SPECIFIC_ORDER'
// Auth
export const AUTH_SUCCESSFUL = 'AUTH_SUCCESSFUL';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const AUTH_START = 'AUTH_START';
export const AUTH_INIT = 'AUTH_INIT';
export const TOKEN_INVALIDATE = 'TOKEN_INVALIDATE';
export const TOKEN_INVALIDATE_INITIATE = 'TOKEN_INVALIDATE_INITIATE';
export const SET_REDIRECT_PATH = 'SET_REDIRECT_PATH'
export const CHECK_AUTH_TOKEN = 'CHECK_AUTH_TOKEN';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_AUTO_LOGIN_TRY  =  'AUTH_AUTO_LOGIN_TRY';